### ISSUE TITLE
Deprication warning

### ISSUE THREAD

**Issue by wulftone** [patshaughnessy/paperclip#4]
I got the following deprication warning when starting up my rails server:

```
DEPRECATION WARNING: Use toplevel init.rb; rails/init.rb is deprecated: C:/myapp/vendor/plugins/paperclip_blob/rails/init.rb. (called from C:/myapp/config/environment.rb:5)
```

Great plugin. Thanks!

**Comment by patshaughnessy** [comment]
Thanks for this... to avoid the warning use paperclip as a gem, not a plugin. I'm not sure I want to remove rails/init.rb since it might cause problems for Rails 2.x apps.

Here's how to use it as a gem:
- remove the plugin: rm -rf vendor/plugins/paperclip
- In your Gemfile:
  gem 'paperclip', :git => 'http://github.com/patshaughnessy/paperclip.git'
- bundle install
- pat
