### ISSUE TITLE
Namespaced Controllers

### ISSUE THREAD

**Issue by wulftone** [patshaughnessy/paperclip#5]
I'm having a lot of trouble getting the "downloads_files_for" to work with a namespaced controller, for example, in my clients controller:

```
class Admin::ClientsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :class => "Admin::Client", :message => "Not authorized"
  downloads_files_for :admin_client, :logo_small
...
```

In database.rb, I tried adding this into downloads_files_for:

```
model_record = model.split('::').reduce(Object){|cls, c| cls.const_get(c)}.find(user_id)
```

and calling it with:

```
downloads_files_for "Admin::Client", :logo_small
```

But it didn't work, even though that way of making a variable class name works in the controller (so i know that method does work somewhere!).

I also know that the image is in the database.  As a temporary fix, I made an additional action:
    def client_logo
      @image = Admin::Client.find(current_user.client_id)
      send_data @image.logo_small_file, :type => 'image/png', :disposition => 'inline'
    end

...and THAT works... but it's not Paperclip.  Any ideas?

Any help would be greatly appreciated.  Thanks!

**Comment by patshaughnessy** [comment]
Hi there... thanks for trying my paperclip fork! Actually your code worked just fine for me... I'm guessing maybe you are missing something in your routes.rb file?

I got it to work as follows... app/models/admin/user.rb:

```
module Admin
  class User < ActiveRecord::Base
    has_attached_file :avatar,
                      :storage => :database,
                      :styles => {
                        :thumb => "75x75>",
                        :small => "150x150>"
                      },
                      :url => '/:class/:id/:attachment?style=:style'

    default_scope select_without_file_columns_for(:avatar)
  end
end
```

app/controller/admin/users_controller.rb:

```
module Admin
  class UsersController < ApplicationController

    downloads_files_for 'Admin::User', :avatar
```

config/routes.rb (maybe you forgot this??):

```
namespace :admin do
  resources :users do
    member do
      get :avatars
    end
  end
end
```

... and that was pretty much it. I also had to adjust my (scaffolding) view code a bit to use "admin_user_path" instead of "user_path"   etc.

Hope this helps... I'll think about adding your change to downloads_files_for. It might make sense to take an optional param to specify the namespace/module, or else we'll need to check whether the model param is a symbol or a string. Your "reduce" code was very cool :)
- pat

**Comment by wulftone** [comment]
Awesome!  Thanks.  This did work.  In fact, the reason my fix didn't work was that it DID work.... The _real_ issue was with the "default scope" and the CanCan authorization system.  Duh.

Love this fork.  Keep it up!
